# Generated by Django 5.1.3 on 2024-11-13 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('operator', 'Оператор'), ('storage', 'Хранилище')], max_length=50)),
                ('glass_total_capacity', models.FloatField()),
                ('glass_current_occupancy', models.FloatField(default=0)),
                ('plastic_total_capacity', models.FloatField()),
                ('plastic_current_occupancy', models.FloatField(default=0)),
                ('biowastes_total_capacity', models.FloatField()),
                ('biowastes_current_occupancy', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('node_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_from', to='storage.node')),
                ('node_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_to', to='storage.node')),
            ],
        ),
    ]
