# Generated by Django 5.1.3 on 2024-11-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='biowastes_total_capacity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='glass_total_capacity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='plastic_total_capacity',
            field=models.FloatField(default=0),
        ),
    ]
